name: simply_queue_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project with Serverpod.
environment: 
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies: 
  cupertino_icons: ^1.0.5
  serverpod_auth_email_flutter: 2.1.5
  serverpod_auth_shared_flutter: 2.1.5
  serverpod_flutter: 2.1.5
  get: 4.6.6
  flutter: 
    sdk: flutter
  simply_queue_client: 
    path: ../simply_queue_client

dev_dependencies: 
  flutter_lints: '>=3.0.0 <6.0.0'
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

